---
- name: Reload iptables
  ansible.builtin.shell:
    cmd: |
      set -e
      iptables-restore --test < {{ vpn_iptables_rules_file }}
      iptables-restore < {{ vpn_iptables_rules_file }}
  changed_when: true

- name: Restart WireGuard
  ansible.builtin.systemd:
    name: "wg-quick@{{ vpn_wg_interface }}"
    state: restarted

- name: Restart node exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    daemon_reload: true

- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
